spring.application.name=payment-service
server.port=8082
stripe.api.secret-test-key=${STRIPE_TEST_SECRET:sk_missing}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
order.service.url=http://localhost:8081/api/v1/orders
user.service.url=http://localhost:8084/api/v1/users
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
security.jwt.secret-key=${SPRING_JWT_SECRET_KEY}