spring.application.name=payment-service
server.port=8082
stripe.api.secret-test-key=${STRIPE_TEST_SECRET:sk_missing}
# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# Other configurations
order.service.url=${ORDER_SERVICE_URL:http://order-service:8081/api/v1}
user.service.url=${USER_SERVICE_URL:http://user-service:8084/api/v1}
security.jwt.secret-key=${JWT_SECRET_KEY}
# Logging
logging.level.org.springframework=INFO
logging.level.com.gostavdev.commercify=DEBUG