services:
  mysql:
    image: mysql:9.1
    container_name: commercify-mysql
    environment:
      - MYSQL_DATABASE=commercifydb
      - MYSQL_USER=commercifyapp
      - MYSQL_PASSWORD=password123!
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  commercify:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: commercify-app
    env_file: .env
    ports:
      - "6091:6091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/commercifydb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MOBILEPAY_MERCHANT_ID=${MOBILEPAY_MERCHANT_ID}
      - MOBILEPAY_CLIENT_ID=${MOBILEPAY_CLIENT_ID}
      - MOBILEPAY_CLIENT_SECRET=${MOBILEPAY_CLIENT_SECRET}
      - MOBILEPAY_SUBSCRIPTION_KEY=${MOBILEPAY_SUBSCRIPTION_KEY}
      - MOBILEPAY_API_URL=${MOBILEPAY_API_URL}
      - MOBILEPAY_SYSTEM_NAME=${MOBILEPAY_SYSTEM_NAME}
      - MOBILEPAY_WEBHOOK_CALLBACK=${MOBILEPAY_WEBHOOK_CALLBACK}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: