spring.application.name=order-service
server.port=8081
# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# Other configurations
user.service.url=${USER_SERVICE_URL:http://user-service:8084/api/v1}
product.service.url=${PRODUCT_SERVICE_URL:http://product-service:8082/api/v1}
payment.service.url=${PAYMENT_SERVICE_URL:http://payment-service:8083/api/v1}
security.jwt.secret-key=${JWT_SECRET_KEY}
# Logging
logging.level.org.springframework=INFO
logging.level.com.gostavdev.commercify=DEBUG