spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3306/orderdb
spring.datasource.username=root
spring.datasource.password=${LOCAL_DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081
product.service.url=http://localhost:8083/api/v1/products
payment.service.url=http://localhost:8082/api/v1/payments
user.service.url=http://localhost:8084/api/v1/users
security.jwt.secret-key=${JWT_SECRET_KEY}