spring.application.name=product-service
server.port=8083
stripe.api.secret-test-key=${STRIPE_TEST_SECRET:sk_missing}
# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# Other configurations
user.service.url=${USER_SERVICE_URL:not-set}
security.jwt.secret-key=${JWT_SECRET_KEY}
# Logging
logging.level.org.springframework=INFO
logging.level.com.gostavdev.commercify=DEBUG